safe: true
pygments: true
permalink: /:category/:year/:month/:day/:title/

url: http://buchanansc.com
title: Scott Buchanan
subtitle: buchanansc.com

twitter:
    user: wafflesnatcha
    limit: 3
github:
    user: wafflesnatcha
    limit: 3
lastfm:
    user: wafflesnatcha
    api_key: 1ad6bea80327069ed4ecccf76fe34175
    limit: 3
    
exclude: ["CNAME", "config.rb", "grunt.js", "Rakefile"]
environment: production