safe: true
pygments: true
permalink: /:categories/:year/:month/:day/:title

url: http://buchanansc.com
title: Scott Buchanan
subtitle: buchanansc.com

author:
    name: Scott Buchanan
    name_given: Scott
    name_family: Buchanan
    github: wafflesnatcha
    twitter: wafflesnatcha
    lastfm: wafflesnatcha
    job_title: Software Engineer
    address:
        locality: San Francisco Bay Area
        region: CA
        country: United States

lastfm_apikey: 1ad6bea80327069ed4ecccf76fe34175

exclude: ["CNAME", "config.rb", "grunt.js", "Rakefile"]
environment: development

