safe: true
pygments: true
permalink: /:categories/:year/:month/:day/:title
url: http://buchanansc.com
exclude: ["CNAME", "grunt.js", "Rakefile"]

me:
    name:
        given: Scott
        family: Buchanan
    address:
        locality: Sacramento
        region: CA
        country: United States
    job_title: Software Engineer
    # resume: /about/resume/
    github: wafflesnatcha
    lastfm: wafflesnatcha
    # twitter: wafflesnatcha

lastfm_apikey: 1ad6bea80327069ed4ecccf76fe34175
environment: production