safe: true
permalink: /:categories/:year/:month/:day/:title
url: https://buchanansc.com
exclude: ["CNAME", "Gruntfile.js", "Rakefile", "package.json", "package_lock.json"]
markdown: kramdown

kramdown:
    use_coderay: true

me:
    name:
        given: Scott
        family: Buchanan
    address:
        locality: Sacramento
        region: CA
        country: United States
    job_title: Software Engineer
    # resume: /about/resume/
    github: buchanansc
    lastfm: wafflesnatcha
    # twitter: wafflesnatcha

google_analytics: false
lastfm_apikey: 1ad6bea80327069ed4ecccf76fe34175
environment: production